const pool = require("../../model/database");

const genres = [
    "Open World",
    "Fantasy",
    "Stealth",
    "Historical",
    "Souls-like",
    "Post-Apocalyptic",
    "Horror",
    "Co-op",
    "Action",
    "FPS",
    "TPS",
    "Fighting",
    "Survival",
    "Beat 'em up",
    "Metroidvania",
    "Party",
    "Simulation",
    "Farming",
    "Roguelike",
    "Hunting",
    "Tower Defense",
    "Building",
    "Sandbox",
    "Battle Royale",
    "Action-Adventure",
    "Adventure",
    "Narrative",
    "Point-and-Click",
    "RPG",
    "War",
    "MMORPG",
    "RTS",
    "TBS",
    "Management",
    "Sports",
    "Racing",
    "Puzzle",
    "Platform",
    "Rhythm",
    "Hack 'n' Slash",
    "Educational",
    "Board",
    "Survival Horror",
    "Science Fiction",
    "MOBA",
    "VR",
    "Multiplayer",
    "Solo",
];

const videoGames = {
    "Call of Duty: Black Ops Cold War": [
        "FPS",
        "Action",
        "War",
        "Narrative",
        "Multiplayer",
        "Co-op",
        "Solo",
    ],
    "FIFA 21": [
        "Sports",
        "Multiplayer",
        "Solo",
        "Co-op"
    ],
    "The Legend of Zelda: Breath of the Wild": [
        "Open World",
        "Fantasy",
        "Action-Adventure",
        "Adventure",
        "Action",
        "Solo",
    ],
    "Cyberpunk 2077": [
        "Open World",
        "Science Fiction",
        "Action-Adventure",
        "Action",
        "RPG",
        "Solo",
        "Adventure",
        "FPS",
        "Narrative",
    ],
    "Red Dead Redemption 2": [
        "Open World",
        "Historical",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Narrative",
        "Solo",
        "Co-op",
        "Multiplayer",
        "TPS",
        "FPS",
    ],
    "The Witcher 3: Wild Hunt": [
        "Open World",
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "RPG",
        "Narrative",
        "Solo",
    ],
    "Grand Theft Auto V": [
        "Open World",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Narrative",
        "Multiplayer",
        "Co-op",
        "Solo",
        "TPS",
        "FPS",
    ],
    "Call of Duty: Modern Warfare": [
        "FPS",
        "Action",
        "War",
        "Narrative",
        "Multiplayer",
        "Co-op",
        "Solo",
    ],
    "Minecraft": [
        "Open World",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Multiplayer",
        "Co-op",
        "Solo",
        "Building",
        "Sandbox",
        "Survival",
    ],
    "Assassin's Creed Valhalla": [
        "Open World",
        "Historical",
        "Action-Adventure",
        "Action",
        "Adventure",
        "RPG",
        "Solo",
        "Stealth",
        "Narrative",
    ],
    "Super Mario Odyssey": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Platform",
        "Solo",
    ],
    "The Elder Scrolls V: Skyrim": [
        "Open World",
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "RPG",
        "Solo",
        "Narrative",
    ],
    "Sekiro: Shadows Die Twice": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Souls-like",
    ],
    "Horizon Zero Dawn": [
        "Open World",
        "Science Fiction",
        "Action-Adventure",
        "Action",
        "Adventure",
        "RPG",
        "Solo",
        "Narrative",
    ],
    "Doom Eternal": [
        "FPS",
        "Action",
        "Action-Adventure",
        "Adventure",
        "Solo",
        "Multiplayer",
        "Co-op",
        "Science Fiction",
        "Platform",
    ],
    "The Last of Us Part II": [
        "Action-Adventure",
        "Horror",
        "Survival Horror",
        "Action",
        "Adventure",
        "Narrative",
        "Solo",
        "Stealth",
        "TPS",
    ],
    "Star Wars Jedi: Fallen Order": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Narrative",
        "Solo",
        "Science Fiction",
        "Souls-like",
        "Metroidvania",
    ],
    "Halo: Infinite": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Multiplayer",
        "Co-op",
        "Science Fiction",
        "FPS",
        "Open World",
    ],
    "Resident Evil Village": [
        "Survival Horror",
        "Horror",
        "Action",
        "Action-Adventure",
        "Adventure",
        "Solo",
        "Narrative",
        "FPS",
    ],
    "Ghost of Tsushima": [
        "Open World",
        "Historical",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Narrative",
        "Stealth",
    ],
    "Final Fantasy VII": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "RPG",
        "Narrative",
        "Solo",
    ],
    "Death Stranding": [
        "Science Fiction",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Narrative",
        "Solo",
        "Open World",
    ],
    "Demon's Souls": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "RPG",
    ],
    "Fallout 4": [
        "Open World",
        "Science Fiction",
        "Action-Adventure",
        "Action",
        "Adventure",
        "RPG",
        "Solo",
        "Narrative",
        "Post-Apocalyptic",
        "FPS",
    ],
    "Genshin Impact": [
        "Open World",
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "RPG",
        "Multiplayer",
        "Co-op",
        "Solo",
    ],
    "Borderlands 3": [
        "Science Fiction",
        "Action-Adventure",
        "Action",
        "Adventure",
        "RPG",
        "Multiplayer",
        "Co-op",
        "Solo",
        "FPS",
    ],
    "The Outer Worlds": [
        "Science Fiction",
        "Action-Adventure",
        "Action",
        "Adventure",
        "RPG",
        "Solo",
        "Narrative",
    ],
    "Control": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Narrative",
        "TPS",
        "Metroidvania",
        "Horror",
    ],
    "The Medium": [
        "Horror",
        "Survival Horror",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Narrative",
        "Solo",
    ],
    "Nioh 2": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "RPG",
        "Multiplayer",
        "Co-op",
        "Solo",
    ],
    "Watch Dogs: Legion": [
        "Open World",
        "Science Fiction",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Narrative",
        "Stealth",
        "TPS",
    ],
    "Bioshock Infinite": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Narrative",
        "FPS",
    ],
    "Dying Light 2 stay human": [
        "Open World",
        "Horror",
        "Survival Horror",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Multiplayer",
        "Co-op",
        "FPS",
    ],
    "Fall Guys: Ultimate Knockout": [
        "Party",
        "Multiplayer",
        "Co-op",
        "Platform",
        "Battle Royale",
    ],
    "God of War I": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Beat 'em up",
        "Fantasy",
    ],
    "God of War II": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Beat 'em up",
        "Fantasy",
    ],
    "God of War: Betrayal": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Beat 'em up",
        "Fantasy",
    ],
    "God of War: Chains of Olympus": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Beat 'em up",
        "Fantasy",
    ],
    "God of War: III": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Beat 'em up",
        "Fantasy",
    ],
    "God of War: Ghost of Sparta": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Beat 'em up",
        "Fantasy",
    ],
    "God of War: Ascension": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Beat 'em up",
        "Fantasy",
    ],
    "God of War": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Hack 'n' Slash",
        "Fantasy",
        "Narrative",
    ],
    "God of War: Ragnarok": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Hack 'n' Slash",
        "Fantasy",
        "Narrative",
    ],
    "God of War III Remastered": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Hack 'n' Slash",
        "Fantasy",
    ],
    "Stardew Valley": [
        "Simulation",
        "Farming",
        "Multiplayer",
        "Co-op",
        "Solo",
        "RPG",
    ],
    "Hades": [
        "Action",
        "Solo",
        "RPG",
        "Hack 'n' Slash",
        "Roguelike",
    ],
    "Baldur's Gate 3": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "RPG",
        "Multiplayer",
        "Co-op",
        "Fantasy",
    ],
    "Monster Hunter: World": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Solo",
        "Multiplayer",
        "Co-op",
        "Fantasy",
        "Hunting",
        "Open World",
        "RPG",
    ],
    "Cyber Shadow": [
        "Action",
        "Solo",
        "Platform",
    ],
    "Animal Crossing: New Horizons": [
        "Simulation",
        "Farming",
        "Multiplayer",
        "Co-op",
        "Solo",
        "Sandbox",
    ],
    "Tom Clancy's Rainbow Six Siege": [
        "FPS",
        "Action",
        "Multiplayer",
        "Co-op",
        "Solo",
    ],
    "Final Fantasy VII Remake": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "RPG",
        "Narrative",
        "Solo",
    ],
    "League of Legends": [
        "MOBA",
        "Action",
        "Multiplayer",
        "Co-op",
    ],
    "Apex Legends": [
        "Battle Royale",
        "Action",
        "Multiplayer",
        "Co-op",
        "FPS",
    ],
    "Among Us": [
        "Party",
        "Multiplayer",
    ],
    "Call of Duty: Warzone": [
        "Battle Royale",
        "Action",
        "Multiplayer",
        "Co-op",
        "FPS",
    ],
    "Fortnite": [
        "Action",
        "Battle Royale",
        "Multiplayer",
        "Co-op",
        "TPS",
    ],
    "Overwatch": [
        "FPS",
        "Action",
        "Multiplayer",
        "Co-op",
    ],
    "Valorant": [
        "FPS",
        "Action",
        "Multiplayer",
        "Co-op",
    ],
    "Destiny 2": [
        "FPS",
        "Action",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Counter-Strike: Global Offensive": [
        "FPS",
        "Action",
        "Multiplayer",
        "Co-op",
    ],
    "Rocket League": [
        "Sports",
        "Multiplayer",
        "Co-op",
    ],
    "Sea of Thieves": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Multiplayer",
        "Co-op",
        "Open World",
    ],
    "World of Warcraft": [
        "MMORPG",
        "Action",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Dead by Daylight": [
        "Horror",
        "Survival Horror",
        "Multiplayer",
        "Co-op",
    ],
    "Phasmophobia": [
        "Horror",
        "Survival Horror",
        "Multiplayer",
        "Co-op",
        "Solo",
        "VR",
    ],
    "The Sims 4": [
        "Simulation",
        "Multiplayer",
        "Co-op",
        "Solo",
        "Building",
    ],
    "Rust": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Multiplayer",
        "Co-op",
        "Survival",
        "Open World",
    ],
    "RuneScape": [
        "MMORPG",
        "Action",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Path of Exile": [
        "Action-Adventure",
        "Action",
        "Adventure",
        "Multiplayer",
        "Co-op",
        "Solo",
        "RPG",
    ],
    "World of Tanks": [
        "Action",
        "Simulation",
        "War",
        "Multiplayer",
        "Co-op",
    ],
    "Warframe": [
        "Action",
        "Multiplayer",
        "Co-op",
        "Solo",
        "RPG",
        "Stealth",
    ],
    "Team Fortress 2": [
        "FPS",
        "Action",
        "Multiplayer",
        "Co-op",
    ],
    "Dota 2": [
        "MOBA",
        "Action",
        "Multiplayer",
        "Co-op",
        "RTS",
    ],
    "Smite": [
        "MOBA",
        "Action",
        "Multiplayer",
        "Co-op",
        "RTS",
    ],
    "Guild Wars 2": [
        "MMORPG",
        "Action",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Arma 3": [
        "FPS",
        "Action",
        "Multiplayer",
        "Co-op",
        "War",
    ],
    "Outlast": [
        "Horror",
        "Survival Horror",
        "Action",
        "Action-Adventure",
        "Adventure",
        "Solo",
    ],
    "The Forest": [
        "Horror",
        "Survival Horror",
        "Action",
        "Action-Adventure",
        "Adventure",
        "Multiplayer",
        "Co-op",
        "Solo",
        "Survival",
    ],
    "Left 4 Dead 2": [
        "Horror",
        "Survival Horror",
        "Action",
        "Action-Adventure",
        "Adventure",
        "Multiplayer",
        "Co-op",
        "Solo",
    ],
    "Among the Sleep": [
        "Horror",
        "Survival Horror",
        "Action",
        "Action-Adventure",
        "Adventure",
        "Solo",
    ],
    "Alien: Isolation": [
        "Horror",
        "Survival Horror",
        "Action",
        "Action-Adventure",
        "Adventure",
        "Solo",
        "Stealth",
        "Science Fiction",
    ],
    "Amnesia: The Dark Descent": [
        "Horror",
        "Survival Horror",
        "Action",
        "Action-Adventure",
        "Adventure",
        "Solo",
    ],
    "The Evil Within": [
        "Horror",
        "Survival Horror",
        "Action",
        "Action-Adventure",
        "Adventure",
        "Solo",
        "Stealth",
        "TPS"
    ],
    "Dead Space": [
        "Horror",
        "Survival Horror",
        "Action",
        "Action-Adventure",
        "Adventure",
        "Solo",
        "Science Fiction",
        "TPS",
    ],
    "Dark Souls": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Dark Souls II": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Dark Souls III": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Bloodborne": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "The Surge": [
        "Science Fiction",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "RPG",
    ],
    "Lords of the Fallen": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Salt and Sanctuary": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
        "Metroidvania",
    ],
    "Hollow Knight": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Metroidvania",
    ],
    "Ashen": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Nioh": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Remnant: From the Ashes": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Blasphemous": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "RPG",
        "Metroidvania",
    ],
    "Code Vein": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Mortal Shell": [
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "RPG",
    ],
    "Elden Ring": [
        "Open World",
        "Fantasy",
        "Action-Adventure",
        "Action",
        "Adventure",
        "Souls-like",
        "Solo",
        "Multiplayer",
        "Co-op",
        "RPG",
    ],
    "Bloons TD 6": [
        "Tower Defense",
        "TBS",
        "Multiplayer",
        "Co-op",
        "Solo",
    ],
    "Squewe Run": [
        "Action",
        "Platform",
        "Solo",
    ],
    "Shrek": [
        "Action",
        "Adventure",
        "Action-Adventure",
        "Platform",
        "Solo",
    ],
    "skerhS": [
        "Action",
        "Adventure",
        "Action-Adventure",
        "Platform",
        "Solo",
    ],
    "Doom": [
        "Action",
        "Solo",
        "FPS",
        "Multiplayer",
        "Co-op",
    ],
    "Doom II": [
        "Action",
        "Solo",
        "FPS",
        "Multiplayer",
        "Co-op",
    ],
    "Doom 3": [
        "Action",
        "Solo",
        "FPS",
        "Horror",
        "Survival Horror",
        "Multiplayer",
        "Co-op",
    ],
    "Doom 64": [
        "Action",
        "Solo",
        "FPS",
    ],
    "Doom (2016)": [
        "Action",
        "Action-Adventure",
        "Adventure",
        "Solo",
        "FPS",
        "Multiplayer",
        "Co-op",
    ],
    "Mighty Doom": [
        "Action",
        "Solo",
    ],
};

async function addGenresToGames() {
    const client = await pool.connect();
    try {
        let query = `INSERT INTO category (genre_id, video_game_id) VALUES `
        for (let i = 0; i < Object.keys(videoGames).length; i++) {
            for (let j = 0; j < videoGames[Object.keys(videoGames)[i]].length; j++) {
                query += `(${genres.indexOf(videoGames[Object.keys(videoGames)[i]][j]) + 1}, ${i + 1}), `
            }
        }
        await client.query(query.slice(0, -2));
    } catch (e) {
        console.error(e);
    } finally {
        client.release();
        await pool.end();
    }
}

addGenresToGames().then(() =>
    console.log("Genres created and added to video games")
);
